name: BreakFast
version: 1.1.2
description: Utility to break blocks with one hit. Optionally drop block after breaking.
main: io.github.jamest.breakfast.BreakFast

commands:
  breakfast:
    description: Enable/disable BreakFast
    aliases: [bf]
    permission: breakfast.use
  breakfastdrop:
    description: Enables/disables drop when using BreakFast
    aliases: [bfd]
    permission: breakfast.use

permissions:
  breakfast.use:
    description: Allows use of BreakFast command.
    default: op